### ISSUE TITLE
What does "payload argument" do?

### ISSUE THREAD

**Issue by nomonkeynodeal** [andzeil/easy-mqtt-handler#4]
Shouldn't the payload argument be an argument for the command being sent?

I'm using xdotool. Wouldn't it make sense to add just one command and then be able to send any xdotool arguments from HA?

Maybe there is a way to do this that I don't understand?

**Comment by andzeil** [comment]
Hey @nomonkeynodeal,

took me a while, but I guess I can clear up your confusion with the release of version 0.1.2, which I just published. Take a look at the updated part of the Readme file here: [https://github.com/andzeil/easy-mqtt-handler/blob/master/](https://github.com/andzeil/easy-mqtt-handler/blob/master/README.md)

Let me know whether this is what you are actually looking for, or if you still need help to get it up and running!

I will btw still need some time to package the Windows Installer, so please bear with me for the moment.

**Comment by andzeil** [comment]
@nomonkeynodeal: Windows build is uploaded, now. Just in case you need it!

**Comment by andzeil** [comment]
Will close this one for now due to no further comments by @nomonkeynodeal.
